logFilters:
  - code: YN0005
    level: discard

nodeLinker: pnp

packageExtensions:
  jest-environment-puppeteer@*:
    peerDependencies:
      puppeteer: "*"
  react-simplemde-editor@*:
    dependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-warning-logger.js
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.3.cjs
