nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-node-version.js

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  terra-ui@*:
    dependencies:
      eslint: "*"
