nodeLinker: node-modules

packageExtensions:
  terra-ui@*:
    dependencies:
      eslint: "*"
  fork-ts-checker-webpack-plugin@*: # to suppress meaningless warnings
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-warning-logger.js

yarnPath: .yarn/releases/yarn-3.0.1.cjs
