logFilters:
  # don't need to warn that we're not running scripts for packages whose only script is attribution
  # we've disabled their scripts to stop them being unplugged by yarn
  - code: YN0005
    level: discard

nodeLinker: pnp

packageExtensions:
  jest-environment-puppeteer@*:
    peerDependencies:
      puppeteer: "*"
  react-simplemde-editor@*:
    dependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-warning-logger.js

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
