nodeLinker: node-modules

packageExtensions:
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  terra-ui@*:
    dependencies:
      eslint: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-warning-logger.js

yarnPath: .yarn/releases/yarn-3.1.1.cjs
