nodeLinker: node-modules

packageExtensions:
  terra-ui@*:
    dependencies:
      eslint: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-node-version.js

yarnPath: .yarn/releases/yarn-3.0.1.cjs
