runtime: nodejs16
default_expiration: "2m"

handlers:
- url: /(.*\.(ico|jpg|jpeg|png|svg))
  static_files: build/\1
  upload: build/(.*)
  secure: always
  # IE has had issues with image files and the X-Content-Type-Options header value, so do not add it to those files.
- url: /(.*\.(css|eot|gz|html|js|json|map|otf|ttf|woff|woff2))
  static_files: build/\1
  upload: build/(.*)
  secure: always
  http_headers:
    X-Content-Type-Options: "nosniff"
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"
