version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    working_directory: /mnt/ramdisk
    docker:
      - image: node:16
        user: node
  puppeteer:
    working_directory: /mnt/ramdisk
    docker:
      - image: circleci/node:16-browsers
  gcloud:
    working_directory: /mnt/ramdisk
    docker:
      - image: google/cloud-sdk:alpine

commands:
  notify-github: # borrows from https://circleci.com/developer/orbs/orb/mmnfst/github-deployments#orb-source
    parameters:
      env:
        type: string
      pr:
        type: boolean
      existing:
        type: boolean
        default: false
    steps:
      - unless:
          condition: << parameters.existing >>
          steps:
            - run:
                name: Notify Github of deployment
                unless: << parameters.existing >>
                command: |
                  apk add github-cli --no-progress --repository=https://dl-cdn.alpinelinux.org/alpine/latest-stable/community/
                  <<# parameters.pr >>
                  VERSION="pr-$(expr "${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}" % 10)"
                  <</ parameters.pr >><<^ parameters.pr >>
                  VERSION="<< parameters.env >>"
                  <</ parameters.pr >>
                  # until https://github.com/cli/cli/issues/1484 is resolved, pass json input:
                  echo "{\"ref\": \"$CIRCLE_BRANCH\", \"environment\": \"$VERSION\", \"auto_merge\": false, \"required_contexts\": []}" \
                    | gh api repos/{owner}/{repo}/deployments -H "Authorization: token $GITHUB_TOKEN" --input - \
                    --jq .id > /tmp/build_num
      - when:
          condition: << parameters.existing >>
          steps:
            - run:
                name: Update Github deployment status
                command: |
                  <<# parameters.pr >>
                  PR_SLUG="pr-$(expr "${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}" % 10)-dot-"
                  <</ parameters.pr >>
                  gh api "repos/{owner}/{repo}/deployments/$(cat /tmp/build_num)/statuses" -H "Authorization: token $GITHUB_TOKEN" \
                    -F state=success -F environment_url="https://${PR_SLUG}bvdp-saturn-<< parameters.env >>.appspot.com" -F log_url="$CIRCLE_BUILD_URL"
            - run:
                name: Update Github deployment status
                when: on_fail
                command: |
                  gh api "repos/{owner}/{repo}/deployments/$(cat /tmp/build_num)/statuses" -H "Authorization: token $GITHUB_TOKEN" -F state=failure

  deploy-env:
    description: "Deploy to a specific environment"
    parameters:
      sa_key_var:
        type: env_var_name
        default: "SA_KEY_JSON"
      env:
        type: string
        default: "dev"
      pr:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: .
      - run: cp config/<< parameters.env >>.json build/config.json
      - run: echo "$<< parameters.sa_key_var >>" > /tmp/sa.json
      - run: gcloud auth activate-service-account --key-file=/tmp/sa.json
      - notify-github:
          env: << parameters.env >>
          pr: << parameters.pr >>
      - when:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy PR
                command: |
                  CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
                  if [[ ! -z "$CIRCLE_PR_NUMBER" ]]; then
                    gcloud app deploy --project=bvdp-saturn-<< parameters.env >> \
                      --version="pr-$(expr "$CIRCLE_PR_NUMBER" % 10)" --no-promote --quiet
                  fi
      - unless:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy << parameters.env >>
                command: gcloud app deploy --project=bvdp-saturn-<< parameters.env >> --promote --quiet
      - notify-github:
          existing: true
          env: << parameters.env >>
          pr: << parameters.pr >>
  integration-tests:
    parameters:
      local:
        type: boolean
        default: false
      env:
        type: string
        default: local
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - test-deps9-{{ checksum "integration-tests/package.json" }}-{{ checksum "integration-tests/yarn.lock" }}
            - test-deps9-
      - run:
          working_directory: integration-tests
          command: yarn install --immutable
      - save_cache:
          key: test-deps9-{{ checksum "integration-tests/package.json" }}-{{ checksum "integration-tests/yarn.lock" }}
          paths:
            - integration-tests/node_modules
            - integration-tests/.yarn/cache
      - when:
          condition: << parameters.local >>
          steps:
            - run: cp config/dev.json build/config.json
            - run:
                command: npx serve build -l 3000
                background: true
            - run: timeout 120 bash -c "until nc -z localhost 3000; do sleep 3; done"
      - run:
          working_directory: integration-tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: "/tmp/test-results/integration-test-results.xml"
            SCREENSHOT_DIR: "/tmp/failure-screenshots"
            ENVIRONMENT: << parameters.env >>
          no_output_timeout: 16m
          command: |
            mkdir -p ${SCREENSHOT_DIR}
            TESTS_TO_RUN=$(circleci tests glob "jest/**.integration-test.js" | circleci tests split --split-by=timings)
            yarn test $TESTS_TO_RUN --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/failure-screenshots
  notify-qa:
    parameters:
      channel:
        type: string
        default: ""
    steps:
      - slack/status:
          channel: << parameters.channel >>
          include_job_number_field: false
          include_project_field: false
          failure_message: ":sadpanda: $CIRCLE_JOB failed."
          success_message: ":circleci-pass: $CIRCLE_JOB ran successfully."

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps8-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - deps8-
      - run: yarn install --immutable
      - save_cache:
          key: deps8-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn/cache
      - run: yarn test
      - run: yarn build
      - run: tar -czf build.tgz .gcloudignore app.yaml build config
      - store_artifacts:
          path: build.tgz
      - persist_to_workspace:
          root: .
          paths:
            - .gcloudignore
            - app.yaml
            - build
            - config
  deploy-pr:
    executor: gcloud
    steps:
      - deploy-env:
          pr: true
  deploy-dev:
    executor: gcloud
    steps:
      - deploy-env
  deploy-alpha:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "ALPHA_SA_KEY_JSON"
          env: "alpha"
      - notify-qa:
          channel: "C7H40L71D" # dsde-qa-notify
  deploy-perf:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "PERF_SA_KEY_JSON"
          env: "perf"
  deploy-staging:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "STAGING_SA_KEY_JSON"
          env: "staging"
      - notify-qa:
          channel: "C7H40L71D" # dsde-qa-notify
  integration-tests-branch-against-dev:
    executor: puppeteer
    parallelism: 4
    steps:
      - integration-tests:
          local: true
          env: local
  integration-tests-alpha:
    executor: puppeteer
    parallelism: 1 # No way to prevent multiple Slack messages otherwise
    steps:
      - integration-tests:
          env: alpha
      - notify-qa
  integration-tests-staging:
    executor: puppeteer
    parallelism: 1 # No way to prevent multiple Slack messages otherwise
    steps:
      - integration-tests:
          env: staging
      - notify-qa

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - integration-tests-branch-against-dev:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-alpha:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-perf:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: dev
  nightly-integration-tests:
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only: dev
    jobs:
      - integration-tests-alpha
      - integration-tests-staging
