version: 2.1

commands:
  deploy-env:
    description: "Deploy to a specific environment"
    parameters:
      sa_key_var:
        type: string
        default: "SA_KEY_JSON"
      env:
        type: string
        default: "dev"
      pr:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: /root/project
      - run: cp config/<< parameters.env >>.json build/config.json
      - run: echo "$<< parameters.sa_key_var >>" > /tmp/sa.json
      - run: gcloud auth activate-service-account --key-file=/tmp/sa.json
      - when:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy PR
                command: |
                  CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
                  if [[ ! -z "$CIRCLE_PR_NUMBER" ]]; then
                    gcloud app deploy --project=bvdp-saturn-<< parameters.env >> \
                      --version="pr-$(expr "$CIRCLE_PR_NUMBER" % 10)" --no-promote --quiet
                  fi
      - unless:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy << parameters.env >>
                command: gcloud app deploy --project=bvdp-saturn-<< parameters.env >> --promote --quiet

jobs:
  test:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ checksum "package.json" }}
            - deps1-
      - run: npm install
      - save_cache:
          key: deps1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - run: tar -czf build.tgz .gcloudignore app.yaml build config
      - store_artifacts:
          path: build.tgz
      - persist_to_workspace:
          root: .
          paths:
            - .gcloudignore
            - app.yaml
            - build
            - config
  deploy-pr:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - deploy-env:
          pr: true
  deploy-dev:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - deploy-env
  deploy-alpha:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - deploy-env:
          sa_key_var: "ALPHA_SA_KEY_JSON"
          env: "alpha"
  deploy-perf:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - deploy-env:
          sa_key_var: "PERF_SA_KEY_JSON"
          env: "perf"
  deploy-staging:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - deploy-env:
          sa_key_var: "STAGING_SA_KEY_JSON"
          env: "staging"

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-alpha:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-perf:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: dev
