version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: |
            npm run build
            tar czf build.tgz app.yaml build config
      - store_artifacts:
          path: build.tgz
      - persist_to_workspace:
          root: .
          paths:
            - app.yaml
            - build
            - config
  deploy-pr:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            cp config/dev.json build/config.json
            echo "$SA_KEY_JSON" > circleci-sa.json
            gcloud auth activate-service-account --key-file=circleci-sa.json
            CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
            if [[ ! -z "$CIRCLE_PR_NUMBER" ]]; then
              gcloud app deploy --project=bvdp-saturn-dev --version="pr-$(expr "$CIRCLE_PR_NUMBER" % 10)" --no-promote --quiet
            fi
  deploy-dev:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - run:
        name: Deploy
        command: |
          cp config/dev.json build/config.json
          echo "$SA_KEY_JSON" > /tmp/sa.json
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          gcloud app deploy --project=bvdp-saturn-dev --promote --quiet
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
