version: 2

jobs:
  test:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm run build
      - run: tar -czf build.tgz app.yaml build config
      - store_artifacts:
          path: build.tgz
      - persist_to_workspace:
          root: /root/project
          paths:
            - app.yaml
            - build
            - config
  deploy-pr:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: /root/project
      - run: cp config/dev.json build/config.json
      - run: echo "$SA_KEY_JSON" > circleci-sa.json
      - run: gcloud auth activate-service-account --key-file=circleci-sa.json
      - run:
          name: Deploy
          command: |
            CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
            if [[ ! -z "$CIRCLE_PR_NUMBER" ]]; then
              gcloud app deploy --project=bvdp-saturn-dev \
                --version="pr-$(expr "$CIRCLE_PR_NUMBER" % 10)" --no-promote --quiet
            fi
  deploy-dev:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: /root/project
      - run: cp config/dev.json build/config.json
      - run: echo "$SA_KEY_JSON" > circleci-sa.json
      - run: gcloud auth activate-service-account --key-file=circleci-sa.json
      - run: gcloud app deploy --project=bvdp-saturn-dev --promote --quiet
  deploy-prod:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run: |
          set -o nounset
          CIRCLE_PROJECTS_URL='https://circleci.com/api/v1.1/projects'
          REPO_URL='https://github.com/DataBiosphere/saturn-ui'
          SELECTOR="[0]['branches']['dev']['last_success']['build_num']"
          LOAD_JSON='json.load(sys.stdin)'
          LAMBDA="lambda x: x['vcs_url'] == '$REPO_URL'"
          PYTHON_CMD='import json; import sys'
          PYTHON_CMD="$PYTHON_CMD; print filter($LAMBDA, $LOAD_JSON)$SELECTOR;"
          PROJECTS="$(curl -s -f -u "${CIRCLE_TOKEN}:" "$CIRCLE_PROJECTS_URL")"
          BUILD_NUM="$(echo "$PROJECTS" | python -c "$PYTHON_CMD")"
          echo "Deploying last successful dev build: $BUILD_NUM"
          ARTIFACT_URL="https://$BUILD_NUM-122538461-gh.circle-artifacts.com"
          ARTIFACT_URL="${ARTIFACT_URL}/0/root/project/build.tgz"
          curl -s -f "$ARTIFACT_URL" | tar -x
          rm build.tgz
          cp config/prod.json build/config.json
          echo "$SA_KEY_JSON" > sa.json
          gcloud auth activate-service-account --key-file=sa.json
          rm sa.json
          gcloud app deploy --project=bvdp-saturn-prod --promote --quiet
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
                - prod
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
