version: 2.1

orbs:
  slack: circleci/slack@3.4.1

executors:
  node:
    docker:
      - image: node:12
        user: node
  puppeteer:
    docker:
      - image: circleci/node:12-browsers
        user: node
  gcloud:
    docker:
      - image: google/cloud-sdk:alpine
  security-scanner:
    docker:
      - image: owasp/zap2docker-weekly

commands:
  deploy-env:
    description: "Deploy to a specific environment"
    parameters:
      sa_key_var:
        type: string
        default: "SA_KEY_JSON"
      env:
        type: string
        default: "dev"
      pr:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: .
      - run: cp config/<< parameters.env >>.json build/config.json
      - run: echo "$<< parameters.sa_key_var >>" > /tmp/sa.json
      - run: gcloud auth activate-service-account --key-file=/tmp/sa.json
      - when:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy PR
                command: |
                  CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"
                  if [[ ! -z "$CIRCLE_PR_NUMBER" ]]; then
                    gcloud app deploy --project=bvdp-saturn-<< parameters.env >> \
                      --version="pr-$(expr "$CIRCLE_PR_NUMBER" % 10)" --no-promote --quiet
                  fi
      - unless:
          condition: << parameters.pr >>
          steps:
            - deploy:
                name: Deploy << parameters.env >>
                command: gcloud app deploy --project=bvdp-saturn-<< parameters.env >> --promote --quiet
  integration-tests:
    parameters:
      local:
        type: boolean
        default: false
      test_url:
        type: string
        default: "http://localhost:3000"
      billing_project:
        type: string
        default: "saturn-integration-test-dev"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - test-deps4-{{ checksum "integration-tests/package.json" }}-{{ checksum "integration-tests/yarn.lock" }}
            - test-deps4-{{ checksum "integration-tests/package.json" }}-
            - test-deps4-
      - run:
          working_directory: integration-tests
          command: yarn install --frozen-lockfile
      - save_cache:
          key: test-deps4-{{ checksum "integration-tests/package.json" }}-{{ checksum "integration-tests/yarn.lock" }}
          paths:
            - integration-tests/node_modules
      - when:
          condition: << parameters.local >>
          steps:
            - run: cp config/dev.json build/config.json
            - run:
                command: npx serve build -l 3000
                background: true
            - run: timeout 120 bash -c "until nc -z localhost 3000; do sleep 3; done"
      - run:
          working_directory: integration-tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: "/tmp/test-results/integration-test-results.xml"
            SCREENSHOT_DIR: "/tmp/failure-screenshots"
            TEST_URL: << parameters.test_url >>
            BILLING_PROJECT: << parameters.billing_project >>
          command: |
            mkdir -p ${SCREENSHOT_DIR}
            yarn test --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/failure-screenshots
  notify-qa:
    steps:
      - slack/status:
          include_job_number_field: false
          include_project_field: false
          failure_message: ":sadpanda: $CIRCLE_JOB failed."
          success_message: ":circleci-pass: $CIRCLE_JOB ran successfully."

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps4-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - deps4-{{ checksum "package.json" }}-
            - deps4-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: deps4-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps4-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - deps4-{{ checksum "package.json" }}-
            - deps4-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: tar -czf build.tgz .gcloudignore app.yaml build config
      - store_artifacts:
          path: build.tgz
      - persist_to_workspace:
          root: .
          paths:
            - .gcloudignore
            - app.yaml
            - build
            - config
  deploy-pr:
    executor: gcloud
    steps:
      - deploy-env:
          pr: true
  deploy-dev:
    executor: gcloud
    steps:
      - deploy-env
  deploy-alpha:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "ALPHA_SA_KEY_JSON"
          env: "alpha"
  deploy-perf:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "PERF_SA_KEY_JSON"
          env: "perf"
  deploy-staging:
    executor: gcloud
    steps:
      - deploy-env:
          sa_key_var: "STAGING_SA_KEY_JSON"
          env: "staging"
  run-dev-security-scans:
    executor: security-scanner
    steps:
      - run:
          name: Run Dev Security Scans
          shell: /bin/bash
          command: |
            docker pull owasp/zap2docker-weekly
            (
              env="https://bvdp-saturn-dev.appspot.com" &&
              docker run -t owasp/zap2docker-weekly zap-baseline.py -t ${env};
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )
  integration-tests-branch-against-dev:
    executor: puppeteer
    steps:
      - integration-tests:
          local: true
  integration-tests-alpha:
    executor: puppeteer
    steps:
      - integration-tests:
          billing_project: "saturn-integration-test-alpha"
          test_url: "https://bvdp-saturn-alpha.appspot.com"
      - notify-qa
  integration-tests-staging:
    executor: puppeteer
    steps:
      - integration-tests:
          billing_project: "saturn-integration-test-stage"
          test_url: "https://bvdp-saturn-staging.appspot.com"
      - notify-qa

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - integration-tests-branch-against-dev:
          requires:
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-pr:
          requires:
            - test
            - build
          filters:
            branches:
              ignore:
                - dev
      - deploy-dev:
          requires:
            - test
            - build
          filters:
            branches:
              only: dev
      - deploy-alpha:
          requires:
            - test
            - build
          filters:
            branches:
              only: dev
      - deploy-perf:
          requires:
            - test
            - build
          filters:
            branches:
              only: dev
      - deploy-staging:
          requires:
            - test
            - build
          filters:
            branches:
              only: dev
  run-security-scans:
    jobs:
      - run-dev-security-scans:
          filters:
            branches:
              only: dev
  nightly-integration-tests:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only: dev
    jobs:
      - integration-tests-alpha
      - integration-tests-staging
