name: Publish Storybook to Chromatic

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build-packages

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # TODO: move to a secret/environment variable
          projectToken: chpt_5aa5b5fb9d15a84
